# Generated by Django 3.2.7 on 2021-09-15 13:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepages',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
